name: deeplearningproject4
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - jupyter>=1.0.0
  - pip